global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "diabetes_mlops_api"
    metrics_path: "/metrics"
    scrape_interval: 5s
    scrape_timeout: 4s
    static_configs:
      - targets: ["api:8000"]
        labels:
          app: "diabetes-mlops-api"
          service: "inference-engine"
          env: "production"
